---
- name: Create Group and user
  hosts: domaincontroller
  vars:
    domain: lostsoulsinc.local

  tasks:
    - name: Create Group
      community.windows.win_domain_group:
        name: corp
        scope: global
        state: present

    - name: Create user
      community.windows.win_domain_user:
        name: jodoe
        firstname: John
        surname: Doe
        password: P@ssw0rd!
        state: present
        groups:
        - corp
